version: '3.8'
services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    networks:
      - psql_network
    environment:
      - IN_DOCKER=1

networks:
  psql_network:
    external: true
